networks:
  aaas-net:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - aaas-net

  auth_agent:
    build: ./core/agents/auth_agent
    ports:
      - "8001:8001"
    volumes:
      - ./core/agents/auth_agent:/app
    depends_on:
      - rabbitmq
    networks:
      - aaas-net

  data_aggregation_agent:
    build: ./core/agents/data_aggregation
    ports:
      - "8002:8002"
    volumes:
      - ./core/agents/data_aggregation:/app
    depends_on:
      - rabbitmq
    networks:
      - aaas-net

  file_monitoring_agent:
    build: ./core/agents/file_monitor
    ports:
     - "8003:8003"
    volumes:
      - ./core/agents/file_monitor:/app
    depends_on:
      - rabbitmq
    networks:
      - aaas-net

  orchestrator_agent:
    build: ./core/agents/orchestrator_agent
    ports:
      - "8000:8000"
    volumes:
      - ./core/agents/orchestrator:/app
    depends_on:
      - rabbitmq
    networks:
      - aaas-net

  security_scanning_agent:
    build: ./core/agents/security_scanner
    ports:
      - "8004:8004"
    volumes:
      - ./core/agents/security_scanner:/app
    depends_on:
      - rabbitmq
    networks:
      - aaas-net 
